import math

print(math.pi)
print(math.e)
print(math.radians(360))
print(math.degrees(math.pi*2))
print(math.sin(math.pi/3))
print(math.sin(math.radians(60)))
print(math.cos(math.pi/3))
print(math.cos(math.radians(60)))
print(math.tan(math.pi/3))
print(math.tan(math.radians(60)))
print(math.sqrt(3))
print(math.pow(7, 3))
print(7 ** 3)
print(math.exp(1))
print(math.pow(math.e, 1))
print(math.e ** 1)
print(math.log(1024, 2))
print(math.log(2))
print(math.log(2, math.e))
print(math.gcd(36, 84))
# print(math.lcm(36, 84, 100))
print(math.fabs(-5))